/**
 * tiny-brains.hash.v1 KAT conformance (EV3-GOV D-EV3-4(5)).
 *
 * The vendored fixture test/providers/fixtures/tiny_brains_hash_v1_kats.json
 * is a byte-meaningful copy of afi-tiny-brains@afa9d5d
 * tests/fixtures/tiny_brains_hash_v1_kats.json — Python-generated by the
 * ACTUAL service implementation (scripts/generate_hash_kats.py over
 * tiny_brains_service/orchestration/invocation_record.py). The reactor
 * verifier MUST reproduce every vector byte-exactly and MUST fail closed on
 * any float outside the proven domain.
 *
 * NOTE: JSON.parse cannot distinguish 0.0 from 0 — the closed /predict/froggy
 * contract declares its single float field (convictionScore), which is why
 * the verifier takes a declared float-key set. The KAT vectors cover the
 * integral forms (0.0, 1.0), the sub-1e-4 exponent forms (1e-06, 5e-05), the
 * decimal threshold (0.0001), shortest-round-trip decimals, key-order
 * insertion independence, and raw-UTF-8 (ensure_ascii=False) strings.
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  PREDICT_FROGGY_FLOAT_KEYS,
  TinyBrainsHashDomainError,
  tinyBrainsCanonicalJson,
  tinyBrainsHashPayload,
} from "../../src/providers/clients/tinyBrainsHashV1.js";

interface KatVector {
  name: string;
  value: unknown;
  canonical: string;
  sha256: string;
}

const fixture = JSON.parse(
  readFileSync(
    join(process.cwd(), "test/providers/fixtures/tiny_brains_hash_v1_kats.json"),
    "utf-8"
  )
) as { law: string; vectors: KatVector[] };

describe("tiny-brains.hash.v1 — Python-generated known-answer vectors", () => {
  it("the fixture is the governed 15-vector suite for the pinned law", () => {
    expect(fixture.law).toBe("tiny-brains.hash.v1");
    expect(fixture.vectors).toHaveLength(15);
  });

  for (const vector of fixture.vectors) {
    it(`reproduces '${vector.name}' byte-exactly (canonical form + digest)`, () => {
      const canonical = tinyBrainsCanonicalJson(vector.value, {
        floatKeys: PREDICT_FROGGY_FLOAT_KEYS,
      });
      expect(canonical).toBe(vector.canonical);
      expect(createHash("sha256").update(canonical, "utf-8").digest("hex")).toBe(vector.sha256);
      expect(
        tinyBrainsHashPayload(vector.value, { floatKeys: PREDICT_FROGGY_FLOAT_KEYS })
      ).toBe(vector.sha256);
    });
  }
});

describe("tiny-brains.hash.v1 — fail-closed outside the proven domain", () => {
  const canon = (value: unknown) =>
    tinyBrainsCanonicalJson(value, { floatKeys: PREDICT_FROGGY_FLOAT_KEYS });

  it("rejects NaN / Infinity", () => {
    expect(() => canon({ convictionScore: Number.NaN })).toThrow(TinyBrainsHashDomainError);
    expect(() => canon({ convictionScore: Infinity })).toThrow(TinyBrainsHashDomainError);
    expect(() => canon({ convictionScore: -Infinity })).toThrow(TinyBrainsHashDomainError);
  });

  it("rejects negative zero", () => {
    expect(() => canon({ convictionScore: -0 })).toThrow(TinyBrainsHashDomainError);
  });

  it("rejects magnitudes at or beyond 1e16 (outside the proven repr domain)", () => {
    expect(() => canon({ convictionScore: 1e16 })).toThrow(TinyBrainsHashDomainError);
    expect(() => canon({ convictionScore: -1e16 })).toThrow(TinyBrainsHashDomainError);
    expect(() => canon({ convictionScore: 123456789012345678 })).toThrow(
      TinyBrainsHashDomainError
    );
  });

  it("rejects lone surrogates (not UTF-8-encodable; Python would throw)", () => {
    expect(() => canon({ note: "bad \ud800 alone" })).toThrow(TinyBrainsHashDomainError);
    expect(() => canon({ "\udfff": "key" })).toThrow(TinyBrainsHashDomainError);
  });

  it("rejects undefined members (absence-not-null contract has no Python form)", () => {
    expect(() => canon({ regime: undefined })).toThrow(TinyBrainsHashDomainError);
  });

  it("sub-1e-4 values that are NOT KAT-covered still take the pinned exponent form", () => {
    // 6-decimal quantized domain values between 1e-06 and 1e-04.
    expect(canon({ convictionScore: 0.000013 })).toBe('{"convictionScore":1.3e-05}');
    expect(canon({ convictionScore: 0.000002 })).toBe('{"convictionScore":2e-06}');
  });
});
